### ISSUE TITLE
ask some detail about multi-gpu support

### ISSUE THREAD

**Issue by stevewyl** [JayYip/m3tl#7] opened 2019-01-08 07:45 UTC
Hi, I'm new to tensorflow, and not quite familiar with multi-GPU training using tf.eatimator. Could you explain some key points that you modify the original code to implement multi-GPU support, especially in the optimizer.py? By the way, is there any big changes in the estimator.py compared with the original code? Thanks in advance!

**Comment by JayYip** [comment] 2019-01-08 07:55
>  Could you explain some key points that you modify the original code to implement multi-GPU support, especially in the optimizer.py?

The original optimizer in bert implements `apply_gradients`, which does not support distribution strategy. For more details, please refer to the link below.
https://github.com/tensorflow/tensorflow/blob/2ca0bf7cf4e16cbed6affd7dd844fea4ed3a62df/tensorflow/python/training/optimizer.py#L530

>  is there any big changes in the estimator.py compared with the original code?

There's a bug in TF 1.12 which is fixed in latest build. I did a simple fix by myself. You can try the estimator from TF 1.12 then you will probably encounter the same error.

**Closed as completed** 2019-01-09 03:46 UTC

**Comment by stevewyl** [comment] 2019-01-09 09:46
@JayYip Thanks for your reply. Another problem, I found you remove the function named _get_variable_name in your optimizer.py, and this function in original code takes param.name as input, but var variable in the _apply_dense function is not a string. Is this the bug you fixed in estimator.py?

**Comment by JayYip** [comment] 2019-01-09 11:53
No, this is not the bug. the `_get_variable_name` is a method to get the slot var name. For more details of implementing optimizer, you may want to google it or post a question on stackoverflow.

**Comment by stevewyl** [comment] 2019-01-10 01:37
@JayYip Ok. I will check it out. But when I ran your program from scratch, the multi-gpu training indeed worked, another problem occurred. The GPU usage is actually 100%, but there is no checkpoint saving during training, and the log stopped updating.

I use the following command to start the program:
"python main.py --problem "CWS|NER|WeiboNER&WeiboSegment" --schedule train"

the nvidia-smi screenshot is:
![image](https://user-images.githubusercontent.com/12755003/50940210-019cbd80-14bb-11e9-9ec9-900d39a043fc.png)
and the log stopped here:
![image](https://user-images.githubusercontent.com/12755003/50940279-3f014b00-14bb-11e9-97ab-f6d58db18880.png)

Thanks!

**Comment by JayYip** [comment] 2019-01-10 01:46
That's weird. May you check the `params.log_every_n_steps` parameters? You can set it to 1 to see whether it's actually training. My guess is that it's actually running normally, maybe your batch size is too large and takes too long to run a step. 

If you're confident this is a bug, please reopen the issue.

**Comment by stevewyl** [comment] 2019-01-10 02:52
@JayYip I set log_every_n_steps to 1 and batch_size is 16. But I still got the same information after I restarted the program for 15 minutes, the gpu memory is full and usage is 100%, no running process showed in nvidia-smi. Then I checked cpu usage, it used about 30% of one core. And I tried "WeiboNER&WeiboSegment" problem, still got the same problem. By the way, how long does your program generally run? I ran the program in docker environment, maybe this is the problem.

**Comment by JayYip** [comment] 2019-01-10 03:15
That is very strange. With batch size of 32, max seq len of 128 the program can run about 3 steps per second on Titan Xp. Could you check the tensorflow logging level and tensorflow version? I don't think this is the reason but you better check. Also, is the checkpoint of step 0 saved?

Normally in training, cpu usage would be around 200% or more. 

I don't think docker is the cause. Because I also run experiments in docker. 

Edit: Could you provide a full log?

**Comment by stevewyl** [comment] 2019-01-10 04:09
@JayYip Frist, I installed the latest nccl tool (2.3.7) according to the instructions in this [blog](https://blog.csdn.net/qq_29592167/article/details/83866840).  

The tf version is 1.12.0, the cuda version is 9.0.176, and checkpoint of step 0 saved successfully. 

The full log is here: 
only WeiboNER 
https://gist.github.com/stevewyl/7c01203a2765641047e4b5b9fc7bf529
WeiboNER& WeiboSegment 
https://gist.github.com/stevewyl/d812761ab8118ca9e5c44e5d05f9a17c

Edit: I reinstall nccl by following the official instruction, the running process now showed in nvidia-smi, however, the program still not running correctly, the log still no more updating after a long while.

**Comment by JayYip** [comment] 2019-01-10 08:11
Everything seems normal. Did you encounter similar problems while training other models?

**Comment by stevewyl** [comment] 2019-01-10 08:14
@JayYip  Nope. The BERT source code runs fine on single GPU.

**Comment by JayYip** [comment] 2019-01-10 08:54
I started from scratch. Clone repo, download pretrained checkpoint, download data, and train. Everything is fine... I am using the official tensorflow r1.12 docker image. 

Is this issue logging level related? The checkpoint will be saved every 10 minutes. Maybe you can let it run for like an hour and see whether there's any checkpoints. 

I have not encounter similar problems training this model or any other models I tried before. I am afraid that I cannot offer more help. Usually the GPU utilization is normal means at least the graph is able to run. If you figured out why, please share with me!

**Comment by stevewyl** [comment] 2019-01-11 09:06
@JayYip Hey, buddy. Sorry to bother you yesterday. The jumper between the graphics cards is not configured. Now the program ran successfully.

**Comment by JayYip** [comment] 2019-01-11 09:22
You are welcome. If you spotted any bugs, please let me know!

**Comment by stevewyl** [comment] 2019-01-12 07:50
@JayYip Hi, I encounter another problem. Referring to your implementation, I try to make run_classifier.py run under multiple GPUs. The program returned an error that position embedding operation cannot be run under the GPU. So I add one line in modeling.py (line 492) and ran successfully.
```python
if use_position_embeddings:
    with tf.device('/cpu:0'): # new line
      assert_op = tf.assert_less_equal(seq_length, max_position_embeddings)
```
But in your implementation, you didn't change anything in modeling.py and successfully built the graph.

If I don not add that line , then the full error information is:
Cannot assign a device for operation bert/embeddings/assert_less_equal/Assert/Assert: Could not satisfy explicit device specification '/replica:0/task:0/device:GPU:0' because no supported kernel for GPU devices is available.

**Comment by JayYip** [comment] 2019-01-12 09:07
I guess that this op has never been run. Please make sure max seq length <= positional embedding size.
